### ISSUE TITLE
GLib-GIO-ERROR **: Settings schema 'org.alsa.scarlettmixer' is not installed

### ISSUE THREAD

**Issue by grinderx** [Oxymoron79/scarlettmixer#1]
Hello,

I just compiled your software, but when trying to run the binary I get this error:

GLib-GIO-ERROR **: Settings schema 'org.alsa.scarlettmixer' is not installed

(Scarlett Mixer:7449): GLib-GIO-ERROR **: Settings schema 'org.alsa.scarlettmixer' is not installed

I 'm attaching the log. I 'm on OpenSuse Leap 42.3.

Thanks,
George

[log.txt](https://github.com/Oxymoron79/scarlettmixer/files/1756287/log.txt)

**Comment by Oxymoron79** [comment]
Hi George,

Did you also run the 
make install
command? Because that should install the settings schema files that the application requires.

Best regards,
Martin

**Comment by grinderx** [comment]
Hello Martin,

make install fails

```
$ make install
Making install in src
make[1]: Entering directory '/home/myuser/scarlettmixer/src'
make  install-am
make[2]: Entering directory '/home/myuser/scarlettmixer/src'
make[3]: Entering directory '/home/myuser/scarlettmixer/src'
 /usr/bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c scarlettmixer '/usr/local/bin'
/usr/bin/install: cannot create regular file '/usr/local/bin/scarlettmixer': Permission denied
Makefile:349: recipe for target 'install-binPROGRAMS' failed
make[3]: *** [install-binPROGRAMS] Error 1
make[3]: Leaving directory '/home/myuser/scarlettmixer/src'
Makefile:663: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/myuser/scarlettmixer/src'
Makefile:657: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/myuser/scarlettmixer/src'
Makefile:445: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

**Comment by Oxymoron79** [comment]
Hi George,

You have to execute the make install command with root privileges. E.g. using sudo:
$ sudo make install
The application will then be installed in /usr/local/bin and can be run with
$ /usr/local/bin/scarlettmixer

Regards,

Martin
